"""
constants — Constantes de SPN IDs y agrupaciones funcionales.

Copia directa del proyecto AWS — no cambia entre nubes.
"""

# --- Velocidad y conducción ---
SPN_VELOCIDAD = 84
SPN_RPM = 190
SPN_ACELERADOR = 91
SPN_FRENO = 521
SPN_MARCHA = 523
SPN_TORQUE = 513
SPN_RETARDER_TORQUE = 520

# --- Combustible y rendimiento ---
SPN_TASA_COMBUSTIBLE = 183
SPN_RENDIMIENTO = 185
SPN_AHORRO_INSTANTANEO = 184
SPN_NIVEL_COMBUSTIBLE = 96
SPN_COMBUSTIBLE_CONSUMIDO = 250

# --- Temperaturas ---
SPN_TEMPERATURA_MOTOR = 110
SPN_TEMPERATURA_ACEITE = 175
SPN_TEMPERATURA_AMBIENTE = 171

# --- Presión y niveles de fluidos ---
SPN_PRESION_ACEITE = 100
SPN_NIVEL_ACEITE = 98
SPN_NIVEL_ANTICONGELANTE = 111
SPN_NIVEL_UREA = 1761

# --- Eléctrico ---
SPN_VOLTAJE_BATERIA = 168

# --- Acumuladores de viaje ---
SPN_ODOMETRO = 917
SPN_HORAS_MOTOR = 247

# --- Balatas ---
SPN_BALATA_DEL_IZQ = 1099
SPN_BALATA_DEL_DER = 1100
SPN_BALATA_TRAS_IZQ1 = 1101
SPN_BALATA_TRAS_DER1 = 1102
SPN_BALATA_TRAS_IZQ2 = 1103
SPN_BALATA_TRAS_DER2 = 1104

# --- Cruise control ---
SPN_CRUISE_CONTROL_STATES = 527
SPN_CRUISE_CONTROL_ENABLE = 596

# --- Agrupaciones funcionales ---

SPNS_COMBUSTIBLE: set[int] = {
    SPN_VELOCIDAD, SPN_RPM, SPN_ACELERADOR, SPN_FRENO, SPN_MARCHA,
    SPN_TORQUE, SPN_RETARDER_TORQUE, SPN_TASA_COMBUSTIBLE,
    SPN_RENDIMIENTO, SPN_AHORRO_INSTANTANEO, SPN_NIVEL_COMBUSTIBLE,
    SPN_COMBUSTIBLE_CONSUMIDO, SPN_CRUISE_CONTROL_STATES,
    SPN_CRUISE_CONTROL_ENABLE, SPN_TEMPERATURA_AMBIENTE,
}

SPNS_MANTENIMIENTO: set[int] = {
    SPN_TEMPERATURA_MOTOR, SPN_TEMPERATURA_ACEITE, SPN_PRESION_ACEITE,
    SPN_NIVEL_ACEITE, SPN_NIVEL_ANTICONGELANTE, SPN_VOLTAJE_BATERIA,
    SPN_NIVEL_UREA, SPN_RETARDER_TORQUE, SPN_ODOMETRO, SPN_HORAS_MOTOR,
    SPN_BALATA_DEL_IZQ, SPN_BALATA_DEL_DER, SPN_BALATA_TRAS_IZQ1,
    SPN_BALATA_TRAS_DER1, SPN_BALATA_TRAS_IZQ2, SPN_BALATA_TRAS_DER2,
    SPN_RPM, SPN_TEMPERATURA_AMBIENTE, SPN_FRENO,
}

SPNS_BALATAS: set[int] = {
    SPN_BALATA_DEL_IZQ, SPN_BALATA_DEL_DER, SPN_BALATA_TRAS_IZQ1,
    SPN_BALATA_TRAS_DER1, SPN_BALATA_TRAS_IZQ2, SPN_BALATA_TRAS_DER2,
}

# Config
GCS_BUCKET = "ado-telemetry-mvp-gcp"
GCS_CATALOGO_KEY = "hackathon-data/catalogo/motor_spn.json"
GCS_VIAJES_KEY = "hackathon-data/simulacion/viajes_consolidados.json"
GCS_FALLAS_KEY = "hackathon-data/fallas-simuladas/data_fault.json"
GCS_FEATURE_NAMES_KEY = "hackathon-data/modelos/sagemaker-v2/training-data/feature_names.json"
FIRESTORE_COLLECTION_TELEMETRIA = "telemetria-live"
FIRESTORE_COLLECTION_ALERTAS = "alertas"
